name: Deploy Node.js API

on:
  push:
    branches:
      - crm_api_nodejs_v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Añadir environment para acceder a los secrets
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify TOKEN_ACCESS environment variable
        run: |
          if [ -z "$TOKEN_ACCESS" ]; then
            echo "ERROR: TOKEN_ACCESS is empty"
            exit 1
          else
            echo "TOKEN_ACCESS is set"
          fi
        env:
          TOKEN_ACCESS: ${{ secrets.TOKEN_ACCESS }}

      - name: Set up SSH and Pull changes
        uses: appleboy/ssh-action@master
        env:
          TOKEN_ACCESS: ${{ secrets.TOKEN_ACCESS }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SCADMINAPIS }}
          port: 22
          envs: TOKEN_ACCESS
          script: |
            # Configurar TOKEN_ACCESS en el ambiente del servidor
            echo "export TOKEN_ACCESS='$TOKEN_ACCESS'" >> ~/.bashrc
            source ~/.bashrc
            
            # Dar permisos a la carpeta del proyecto
            sudo chown -R $USER:$USER /var/www/crm_api_v2
            sudo chmod -R 755 /var/www/crm_api_v2
            
            # Navegar al directorio del proyecto
            cd /var/www/crm_api_v2
            
            # Configurar Git
            git config --global user.email "soporte@roccacr.com"
            git config --global user.name "roccacr"
            
            # Guardar cambios locales
            sudo git stash
            
            # Pull del último código
            git pull https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/roccacr/CRM_VENTAS.git crm_api_nodejs_v2
            
            # Configurar NVM y Node.js
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 18
            
            # Reiniciar PM2
            /home/ubuntu/.nvm/versions/node/v18.17.1/bin/pm2 restart 1