name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - crm_api_nodejs_v2  # Cambia esto por la rama que estés utilizando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Versión de Node.js que estés usando

      - name: Install dependencies
        run: npm install

      # Eliminar el paso de build ya que no es necesario
      # - name: Run the build
      #   run: npm run build

      - name: Start application with PM2
        run: pm2 start ecosystem.config.js  # Cambia esto según tu archivo de configuración de PM2
        env:
          TOKEN_ACCESS: ${{ secrets.TOKEN_ACCESS }}  # Esto carga el secreto en la variable de entorno

      - name: Show PM2 status
        run: pm2 status
