name: CI/CD Pipeline

on:
  push:
    branches:
      - crm_node_v2  # Ejecutar el workflow en la rama crm_node_v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the build
        run: npm run build
        env:
          DB_PASS_PRODUCTION: ${{ secrets.DB_PASS_PRODUCTION }}

      - name: Run tests
        run: npm test
        env:
          DB_PASS_PRODUCTION: ${{ secrets.DB_PASS_PRODUCTION }}

