name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - crm_api_nodejs_v2  # Cambia esto por la rama que estés utilizando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso para hacer checkout del código del repositorio
      - name: Check out the repository
        uses: actions/checkout@v2

      # Paso de depuración para verificar que el secreto se pasa correctamente
      - name: Verify TOKEN_ACCESS environment variable
        run: |
          if [ -z "$TOKEN_ACCESS" ]; then
            echo "TOKEN_ACCESS is not set"
            exit 1
          else
            echo "TOKEN_ACCESS esta definida"
          fi
        env:
          TOKEN_ACCESS: ${{ secrets.TOKEN_ACCESS }}  # Asegúrate de que el secreto esté disponible como variable de entorno
