name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - crm_api_nodejs_v2  # Cambia esto por la rama que estés utilizando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out del repositorio
      - name: Check out the repository
        uses: actions/checkout@v2

      # Paso 2: Verificar el valor del token en el pipeline
      - name: Verify TOKEN_ACCESS environment variable
        run: |
          if [ -z "$TOKEN_ACCESS" ]; then
            echo "TOKEN_ACCESS is not set"
            exit 1
          else
            echo "TOKEN_ACCESS esta definida"
          fi
        env:
          TOKEN_ACCESS: "holaaaaaaaaaa"  # Definición de TOKEN_ACCESS

      # Paso 3: Conectar vía SSH y desplegar en el servidor remoto
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.6  # Usa la acción SSH para conectarse al servidor
        with:
          host: ${{ secrets.SERVER_IP }}  # IP del servidor, almacenada en un 'secret'
          username: ${{ secrets.SERVER_USER }}  # Usuario del servidor, almacenado en un 'secret'
          key: ${{ secrets.SCADMINAPIS }}  # Clave privada SSH, almacenada en un 'secret'
          port: 22  # Puerto SSH (por defecto, 22)
          envs:  # Definimos las variables de entorno que se pasarán al servidor remoto
            TOKEN_ACCESS: 'holaaaaaaaaaa'

          script: |
            # Navegar al directorio de la aplicación
            cd /var/www/crm_api_v2

            # Hacer un log para verificar si TOKEN_ACCESS se exportó correctamente
            echo "El valor de TOKEN_ACCESS es: $TOKEN_ACCESS"
